### PR TITLE
fix #6419

### LINKED ISSUE #6419: [BUG] Editor Button "Monospaced" Throws JS Error
**Click the "Monospaced" button in the Editor**
Result: The red overlay for internal JavaScript Errors states
> TypeError: can't access property "prefix", operation.paramObject is undefined

**To Reproduce**
1. Load the 5.2.2 prerelease 
2. Create a new tiddler or edit an existing tiddler
3. Select text or just click into the edit area of the text field
4. Click the button to format monospaced text.
5. See error

**Expected behavior**
The button should surround existing text or the cursor with tripple backticks.

**Screenshots**

**TiddlyWiki Configuration**
 - Version 5.2.2 prerelease
 
**Seen on Desktop and Mobile**
 - Mac OS FireFox Developer Edition
 - Chrome on Android

### PR DESCRIPTION
**Pull request by saqimtiaz**
Fix the bug introduced in https://github.com/Jermolene/TiddlyWiki5/commit/88812092fd8fa7da18e6da77f9c410338469cc4e

Fixes #6419

### CODE REVIEW

File: core/modules/editor/operations/text/wrap-lines.js [hunk 1]
```diff
@@ -13,8 +13,8 @@ Text editor operation to wrap the selected lines with a prefix and suffix
 "use strict";
 
 exports["wrap-lines"] = function(event,operation) {
-	var prefix = operation.paramObject.prefix || "",
-		suffix = operation.paramObject.suffix || "";
+	var prefix = event.paramObject.prefix || "",
```
Comment (Jermolene) [inline core/modules/editor/operations/text/wrap-lines.js:16]: Might we need to check for event.paramObject being undefined?

Comment (saqimtiaz) [reply core/modules/editor/operations/text/wrap-lines.js:16]: @Jermolene I considered that but it should not be needed, see https://github.com/Jermolene/TiddlyWiki5/blob/9fce8153dfdd5e2378f1827425c5b1ebbd265df1/core/modules/widgets/action-sendmessage.js#L61-L65

Comment (Jermolene) [reply core/modules/editor/operations/text/wrap-lines.js:16]: Great thanks @saqimtiaz
