### PR TITLE
Fix action-listops unsafe use of $tw.utils.stringifyList()

### LINKED ISSUE #6535: [BUG] ActionListOpsWidget breaks with input titles starting with a dash
The `<$action-listops>` widget breaks with input titles starting with a dash. For example, if the tiddler "target" contains the text `-3` then the following will not work as expected:

```
<$action-listops  $tiddler="target" $field="text" $subfilter="+[toggle[-3]]"/>
```

In this case, the text field of "target" is not left untouched, and the "-3" item is not removed.

But, the same experiment with "foobar" instead of "-3" works as expected.

The problem is here:

https://github.com/Jermolene/TiddlyWiki5/blob/c741978e959c2608fa01dcd881d47194ccdf79b8/core/modules/widgets/action-listops.js#L72-L76

The code makes the assumption that a stringified list can be evaluated as a filter and will get the same results. That assumption fails if the list item starts with a dash, as it is interpreted as the `:except` filter run prefix.

### PR DESCRIPTION
**Pull request by Jermolene**
Fixes #6535

### CODE REVIEW

File: core/modules/widgets/action-listops.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
+const { makeTiddlerIterator } = require("../wiki");
```
Comment (pmario) [inline core/modules/widgets/action-listops.js:1]: Do we allow `const` now?

Comment (Jermolene) [reply core/modules/widgets/action-listops.js:1]: Wow!! No it's much weirder than that – I didn't (intentionally) write that line of code at all,  as far as I can figure out, it was automatically inserted by VSCode and/or GitHub Copilot.

Comment (Jermolene) [reply core/modules/widgets/action-listops.js:1]: I've pushed a fix in 681f22b66d1e37c1f4bbaf900ed41b3036e8ae81

Comment (pmario) [reply core/modules/widgets/action-listops.js:1]: hihi, .. Yea I did disable Copilot again. It did add too much unwanted code and the "autocomplete feature" was constantly interrupting my thought process while programming.

Comment (Jermolene) [reply core/modules/widgets/action-listops.js:1]: It's equally terrifying and hilarious. It does quite well for the kinds of things I might otherwise have to google, and sometimes thrills me by suggesting very TW-specific idioms, like `$tw.utils.stringifyList()`
