### PR TITLE
Fixes bug in correctly resolving functions in text substitutions

### LINKED ISSUE #9188: [BUG] Substitute operator does not correctly resolve functions when substituting variables
When substituting a `$(varname)$` placeholder using the `substitute[]` operator, where `varname` is a function, the function does not have access to variables set in the filter run (`currentTiddler`, `index,` etc). Substitutions for filtered experssions work as expected.

This is discrepancy is likely because the [wiki.getSubstitutedText](https://github.com/TiddlyWiki/TiddlyWiki5/blob/master/core/modules/wiki.js#L1161) method predates functions and just calls `widget.getVariable` to resolve variable references for substitution:

https://github.com/TiddlyWiki/TiddlyWiki5/blob/8ab4306b52711124787dd24b0e803463f21d0f8b/core/modules/wiki.js#L1175-L1178

Instead we probably want to do something along these lines:

```javascript
// Substitute any variable references with their values
return output.replace(/\$\((.+?)\)\$/g, function(match,varname) {
		var variableInfo = widget.getVariableInfo(varname,{defaultValue: ""}),
			srcVariable = variableInfo && variableInfo.srcVariable;
		return  (variableInfo.resultList ? variableInfo.resultList[0] : variableInfo.text) || "";
});

```

### Questions and concerns:
I am pressed for time at present and have not had the time to consider:
- Whether we need to take into account variable/function parameters. 
  - Do we support parameters for variables being substituted. e.g. `$(varname myparam)$` ?
- What would be the possible ramifications of adapting `widget.getVariable` to properly evaluate functions?
- Are there any repercussions for substituted attributes because of this change?

### To reproduce:

```

\function getIndex() [<index>add[1]] 

\procedure template-with-var() $(getIndex)$

\procedure template-with-filteredexpression() ${ [<getIndex>] }$

\function test-with-substitute-variable()
[[abc]split[]] :map[<template-with-var>substitute[]] :and[join[ / ]]
\end

\function test-with-substitute-filteredexpression()
[[abc]split[]] :map[<template-with-filteredexpression>substitute[]] :and[join[ / ]]
\end

\function test-with-function()
[[abc]split[]] :map[function[getIndex]substitute[]] :and[join[ / ]]
\end


!! Test with substitute (variable)
<<test-with-substitute-variable>>

!! Test with substitute (filtered expression):
<<test-with-substitute-filteredexpression>>

!! Test with function:
<<test-with-function>>

```

All three test functions should return the same output: ` 1 / 2 / 3`. but `test-with-substitute-variable` returns `1 / 1 / 1` because the value of `index` in `getIndex` is an empty string, i.e. the variable is undefined. (TiddlyWiki v5.3.7)

### PR DESCRIPTION
**Pull request by saqimtiaz**
This fixes a bug with the resolution of functions within the substitute operator, where the function did not have access to variables set in the filter run. A new test has been added for this scenario.

Closes #9188.

### CODE REVIEW

File: core/modules/wiki.js [hunk 1]
```diff
@@ -1122,23 +1122,24 @@ Parse a block of text of a specified MIME type
 Options include:
 	substitutions: an optional array of substitutions
 */
-exports.getSubstitutedText = function(text,widget,options) {
+exports.getSubstitutedText = function(text,thisWidget,options) {
```
Comment (pmario) [inline core/modules/wiki.js:1125]: Can we change the function signature, without a backwards compatibility problem?

Comment (saqimtiaz) [reply core/modules/wiki.js:1125]: Since we are only changing the variable name assigned to one of the arguments internally, this should not impact backwards compatibility.
