### PR TITLE
Fix undefined xhr bug

### LINKED ISSUE #3261: Internal JavaScript Error
Getting this with the current Github clone.

Internal JavaScript Error
Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
TypeError: xhr is undefined

### PR DESCRIPTION
**Pull request by sukima**
Closes #3261

Bug introduced in commit f9be41720 ("Minor tweak for RetrieveETag (#3257)", 2018-05-05)

### CODE REVIEW

File: core/modules/savers/put.js [hunk 1]
```diff
@@ -25,10 +25,10 @@ var RetrieveETag = function(self) {
 		type: "HEAD",
 		headers: headers,
 		callback: function(err, data, xhr) {
+			if(err) return;
 			var etag = xhr.getResponseHeader("ETag");
-			if(!err && etag) {
-				self.etag = etag.replace(/^W\//,"");
-			}
+			if(!etag) return;
+			self.etag = etag.replace(/^W\//,"");
```
Comment (pmario) [inline core/modules/savers/put.js]: I think, we need to fix line 56 and not here.

**Comment by pmario** [comment]
@Jermolene ... This Issue is critical! We've introduced a "breaking change", that will cause a "RSOD" whenever someone starts a node version or opens TW from a http(s) site.

**Comment by Jermolene** [comment]
Thanks @sukima @pmario
